//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mappy.System.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mappy.Controllers.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Flag.
        /// </summary>
        internal static string AddFlag {
            get {
                return ResourceManager.GetString("AddFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aethernet Color.
        /// </summary>
        internal static string AethernetColor {
            get {
                return ResourceManager.GetString("AethernetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetheryte Color.
        /// </summary>
        internal static string AetheryteColor {
            get {
                return ResourceManager.GetString("AetheryteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Aetherytes on Top.
        /// </summary>
        internal static string AetherytesOnTop {
            get {
                return ResourceManager.GetString("AetherytesOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Members.
        /// </summary>
        internal static string AllianceMembers {
            get {
                return ResourceManager.GetString("AllianceMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Zoom on Hover.
        /// </summary>
        internal static string AllowZoomOnHover {
            get {
                return ResourceManager.GetString("AllowZoomOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Show Toolbar.
        /// </summary>
        internal static string AlwaysShowToolbar {
            get {
                return ResourceManager.GetString("AlwaysShowToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot teleport in this situation..
        /// </summary>
        internal static string CannotTeleport {
            get {
                return ResourceManager.GetString("CannotTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Map.
        /// </summary>
        internal static string CenterMap {
            get {
                return ResourceManager.GetString("CenterMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center on Open.
        /// </summary>
        internal static string CenterOnOpen {
            get {
                return ResourceManager.GetString("CenterOnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers the map when opening it.
        /// </summary>
        internal static string CenterOnOpenHelp {
            get {
                return ResourceManager.GetString("CenterOnOpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center on Player.
        /// </summary>
        internal static string CenterOnPlayer {
            get {
                return ResourceManager.GetString("CenterOnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Color.
        /// </summary>
        internal static string CircleColor {
            get {
                return ResourceManager.GetString("CircleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Map Window.
        /// </summary>
        internal static string CloseMapWindow {
            get {
                return ResourceManager.GetString("CloseMapWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone Angle.
        /// </summary>
        internal static string ConeAngle {
            get {
                return ResourceManager.GetString("ConeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone Radius.
        /// </summary>
        internal static string ConeRadius {
            get {
                return ResourceManager.GetString("ConeRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directional Marker.
        /// </summary>
        internal static string DirectionalMarker {
            get {
                return ResourceManager.GetString("DirectionalMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the module.
        /// </summary>
        internal static string DisableModuleHelp {
            get {
                return ResourceManager.GetString("DisableModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling.
        /// </summary>
        internal static string Disabling {
            get {
                return ResourceManager.GetString("Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed Markers.
        /// </summary>
        internal static string DisplayedMarkers {
            get {
                return ResourceManager.GetString("DisplayedMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Job Icons.
        /// </summary>
        internal static string DisplayJobIcons {
            get {
                return ResourceManager.GetString("DisplayJobIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the players job icon on the map instead of the selected icon.
        /// </summary>
        internal static string DisplayJobIconsHelp {
            get {
                return ResourceManager.GetString("DisplayJobIconsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Options.
        /// </summary>
        internal static string DisplayOptions {
            get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Threshold.
        /// </summary>
        internal static string DistanceThreshold {
            get {
                return ResourceManager.GetString("DistanceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Warning Time.
        /// </summary>
        internal static string EarlyWarningTime {
            get {
                return ResourceManager.GetString("EarlyWarningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Integrations.
        /// </summary>
        internal static string EnableIntegrations {
            get {
                return ResourceManager.GetString("EnableIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the module.
        /// </summary>
        internal static string EnableModuleHelp {
            get {
                return ResourceManager.GetString("EnableModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling.
        /// </summary>
        internal static string Enabling {
            get {
                return ResourceManager.GetString("Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiringColor.
        /// </summary>
        internal static string ExpiringColor {
            get {
                return ResourceManager.GetString("ExpiringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Warning.
        /// </summary>
        internal static string ExpiringWarning {
            get {
                return ResourceManager.GetString("ExpiringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Mode.
        /// </summary>
        internal static string FadeMode {
            get {
                return ResourceManager.GetString("FadeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Options.
        /// </summary>
        internal static string FadeOptions {
            get {
                return ResourceManager.GetString("FadeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Opacity.
        /// </summary>
        internal static string FadePercent {
            get {
                return ResourceManager.GetString("FadePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade When Moving.
        /// </summary>
        internal static string FadeWhenMoving {
            get {
                return ResourceManager.GetString("FadeWhenMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade When Unfocused.
        /// </summary>
        internal static string FadeWhenUnfocused {
            get {
                return ResourceManager.GetString("FadeWhenUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATEs.
        /// </summary>
        internal static string FATEs {
            get {
                return ResourceManager.GetString("FATEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Color.
        /// </summary>
        internal static string FillColor {
            get {
                return ResourceManager.GetString("FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        internal static string Fishing {
            get {
                return ResourceManager.GetString("Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Marker.
        /// </summary>
        internal static string FlagMarker {
            get {
                return ResourceManager.GetString("FlagMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center on Links.
        /// </summary>
        internal static string FocusObjective {
            get {
                return ResourceManager.GetString("FocusObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center and zoom in on target when clicking a link.
        /// </summary>
        internal static string FocusObjectiveHelp {
            get {
                return ResourceManager.GetString("FocusObjectiveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow on Open.
        /// </summary>
        internal static string FollowOnOpen {
            get {
                return ResourceManager.GetString("FollowOnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Follow Player when opening the map.
        /// </summary>
        internal static string FollowOnOpenHelp {
            get {
                return ResourceManager.GetString("FollowOnOpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Player.
        /// </summary>
        internal static string FollowPlayer {
            get {
                return ResourceManager.GetString("FollowPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Integrations.
        /// </summary>
        internal static string GameIntegrations {
            get {
                return ResourceManager.GetString("GameIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Area.
        /// </summary>
        internal static string GatheringArea {
            get {
                return ResourceManager.GetString("GatheringArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Points.
        /// </summary>
        internal static string GatheringPoints {
            get {
                return ResourceManager.GetString("GatheringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gil.
        /// </summary>
        internal static string gil {
            get {
                return ResourceManager.GetString("gil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers map on specified &quot;X, Y&quot; coordinates.
        /// </summary>
        internal static string GoToCommandHelp {
            get {
                return ResourceManager.GetString("GoToCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvesting.
        /// </summary>
        internal static string Harvesting {
            get {
                return ResourceManager.GetString("Harvesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help message.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Accepted Quests.
        /// </summary>
        internal static string HideAcceptedQuests {
            get {
                return ResourceManager.GetString("HideAcceptedQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Frame and Lock Window .
        /// </summary>
        internal static string HideAndLock {
            get {
                return ResourceManager.GetString("HideAndLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Between Areas.
        /// </summary>
        internal static string HideBetweenAreas {
            get {
                return ResourceManager.GetString("HideBetweenAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Combat.
        /// </summary>
        internal static string HideInCombat {
            get {
                return ResourceManager.GetString("HideInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Duties.
        /// </summary>
        internal static string HideInDuties {
            get {
                return ResourceManager.GetString("HideInDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Levequests.
        /// </summary>
        internal static string HideLeveQuests {
            get {
                return ResourceManager.GetString("HideLeveQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Unaccepted Quests.
        /// </summary>
        internal static string HideUnacceptedQuests {
            get {
                return ResourceManager.GetString("HideUnacceptedQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window Frame.
        /// </summary>
        internal static string HideWindowFrame {
            get {
                return ResourceManager.GetString("HideWindowFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide With Game GUI.
        /// </summary>
        internal static string HideWithGameGui {
            get {
                return ResourceManager.GetString("HideWithGameGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostiles.
        /// </summary>
        internal static string Hostiles {
            get {
                return ResourceManager.GetString("Hostiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses.
        /// </summary>
        internal static string HousingMarkers {
            get {
                return ResourceManager.GetString("HousingMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Configuration.
        /// </summary>
        internal static string IconConfig {
            get {
                return ResourceManager.GetString("IconConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tab allows you to disable showing any icon that Mappy has shown you
        ///Icons that you haven&apos;t seen yet can not be disabled.
        /// </summary>
        internal static string IconDisableInfo {
            get {
                return ResourceManager.GetString("IconDisableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No icons have been seen yet
        ///Open Map Window to populate data.
        /// </summary>
        internal static string IconDisableNoIcons {
            get {
                return ResourceManager.GetString("IconDisableNoIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string IconScale {
            get {
                return ResourceManager.GetString("IconScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Selection.
        /// </summary>
        internal static string IconSelection {
            get {
                return ResourceManager.GetString("IconSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Escape Key.
        /// </summary>
        internal static string IgnoreEscapeKey {
            get {
                return ResourceManager.GetString("IgnoreEscapeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents the escape key from closing the Map Window.
        /// </summary>
        internal static string IgnoreEscapeKeyHelp {
            get {
                return ResourceManager.GetString("IgnoreEscapeKeyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Journal Visibility Setting.
        /// </summary>
        internal static string IgnoreJournalSetting {
            get {
                return ResourceManager.GetString("IgnoreJournalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignores the visibility setting in the journal and shows all quests..
        /// </summary>
        internal static string IgnoreJournalSettingHelp {
            get {
                return ResourceManager.GetString("IgnoreJournalSettingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Quest Color.
        /// </summary>
        internal static string InProgressColor {
            get {
                return ResourceManager.GetString("InProgressColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Link Color.
        /// </summary>
        internal static string InstanceLinkColor {
            get {
                return ResourceManager.GetString("InstanceLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces all of the games normal map functions with Mappy functions instead.
        /// </summary>
        internal static string IntegrationsDescription {
            get {
                return ResourceManager.GetString("IntegrationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island Sanctuary.
        /// </summary>
        internal static string IslandSanctuary {
            get {
                return ResourceManager.GetString("IslandSanctuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Open.
        /// </summary>
        internal static string KeepOpen {
            get {
                return ResourceManager.GetString("KeepOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the order that markers are drawn, higher values will be shown on top of lower values..
        /// </summary>
        internal static string LayerHelp {
            get {
                return ResourceManager.GetString("LayerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest Color.
        /// </summary>
        internal static string LeveQuestColor {
            get {
                return ResourceManager.GetString("LeveQuestColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Window Position.
        /// </summary>
        internal static string LockWindow {
            get {
                return ResourceManager.GetString("LockWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Layers.
        /// </summary>
        internal static string MapLayers {
            get {
                return ResourceManager.GetString("MapLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Link Color.
        /// </summary>
        internal static string MapLinkColor {
            get {
                return ResourceManager.GetString("MapLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Markers.
        /// </summary>
        internal static string MapMarkers {
            get {
                return ResourceManager.GetString("MapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining.
        /// </summary>
        internal static string Mining {
            get {
                return ResourceManager.GetString("Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Markers.
        /// </summary>
        internal static string MiscMarkers {
            get {
                return ResourceManager.GetString("MiscMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Colors.
        /// </summary>
        internal static string ModuleColors {
            get {
                return ResourceManager.GetString("ModuleColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Config.
        /// </summary>
        internal static string ModuleConfig {
            get {
                return ResourceManager.GetString("ModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Options.
        /// </summary>
        internal static string ModuleOptions {
            get {
                return ResourceManager.GetString("ModuleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Flag Here.
        /// </summary>
        internal static string MoveFlag {
            get {
                return ResourceManager.GetString("MoveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layers for this map.
        /// </summary>
        internal static string NoLayersInfo {
            get {
                return ResourceManager.GetString("NoLayersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration Window.
        /// </summary>
        internal static string OpenConfigWindow {
            get {
                return ResourceManager.GetString("OpenConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open IPC Demo.
        /// </summary>
        internal static string OpenIPCDemo {
            get {
                return ResourceManager.GetString("OpenIPCDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Map Window.
        /// </summary>
        internal static string OpenMapWindow {
            get {
                return ResourceManager.GetString("OpenMapWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Color.
        /// </summary>
        internal static string OutlineColor {
            get {
                return ResourceManager.GetString("OutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Thickness.
        /// </summary>
        internal static string OutlineThickness {
            get {
                return ResourceManager.GetString("OutlineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Members.
        /// </summary>
        internal static string PartyMembers {
            get {
                return ResourceManager.GetString("PartyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        internal static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Integrations.
        /// </summary>
        internal static string PluginIntegrations {
            get {
                return ResourceManager.GetString("PluginIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappy is not available in PvP..
        /// </summary>
        internal static string PvPError {
            get {
                return ResourceManager.GetString("PvPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarrying.
        /// </summary>
        internal static string Quarrying {
            get {
                return ResourceManager.GetString("Quarrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string QuestMarkers {
            get {
                return ResourceManager.GetString("QuestMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Command Marker.
        /// </summary>
        internal static string RemoveCommandMarker {
            get {
                return ResourceManager.GetString("RemoveCommandMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Flag.
        /// </summary>
        internal static string RemoveFlag {
            get {
                return ResourceManager.GetString("RemoveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Marked Area.
        /// </summary>
        internal static string RemoveGatheringArea {
            get {
                return ResourceManager.GetString("RemoveGatheringArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Quest Marker.
        /// </summary>
        internal static string RemoveQuestMarker {
            get {
                return ResourceManager.GetString("RemoveQuestMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Map Zoom.
        /// </summary>
        internal static string ScaleCone {
            get {
                return ResourceManager.GetString("ScaleCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle will affect whether cone changes size when zooming in/out on map.
        /// </summary>
        internal static string ScaleConeHelp {
            get {
                return ResourceManager.GetString("ScaleConeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Region.
        /// </summary>
        internal static string SearchByRegion {
            get {
                return ResourceManager.GetString("SearchByRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Name.
        /// </summary>
        internal static string SearchForMap {
            get {
                return ResourceManager.GetString("SearchForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Frame and Unlock Window.
        /// </summary>
        internal static string ShowAndUnlock {
            get {
                return ResourceManager.GetString("ShowAndUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cone.
        /// </summary>
        internal static string ShowCone {
            get {
                return ResourceManager.GetString("ShowCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show housing number.
        /// </summary>
        internal static string ShowHousingNumber {
            get {
                return ResourceManager.GetString("ShowHousingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon.
        /// </summary>
        internal static string ShowIcon {
            get {
                return ResourceManager.GetString("ShowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Map Name.
        /// </summary>
        internal static string ShowMapName {
            get {
                return ResourceManager.GetString("ShowMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Misc Tooltips.
        /// </summary>
        internal static string ShowMiscTooltips {
            get {
                return ResourceManager.GetString("ShowMiscTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows tooltips for map icons such as &quot;Repair&quot;, &quot;Shop&quot;, &quot;Trader&quot;.
        /// </summary>
        internal static string ShowMiscTooltipsHelp {
            get {
                return ResourceManager.GetString("ShowMiscTooltipsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Circle.
        /// </summary>
        internal static string ShowRing {
            get {
                return ResourceManager.GetString("ShowRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Teleport Costs.
        /// </summary>
        internal static string ShowTeleportCosts {
            get {
                return ResourceManager.GetString("ShowTeleportCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toolbar on Hover.
        /// </summary>
        internal static string ShowToolbarOnHover {
            get {
                return ResourceManager.GetString("ShowToolbarOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltip.
        /// </summary>
        internal static string ShowTooltip {
            get {
                return ResourceManager.GetString("ShowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Marker Color.
        /// </summary>
        internal static string StandardColor {
            get {
                return ResourceManager.GetString("StandardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport cost.
        /// </summary>
        internal static string TeleportCost {
            get {
                return ResourceManager.GetString("TeleportCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the teleport function, you must install the &apos;Teleporter&apos; plugin.
        /// </summary>
        internal static string TeleporterMissingError {
            get {
                return ResourceManager.GetString("TeleporterMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting to {0}.
        /// </summary>
        internal static string TeleportingToLocation {
            get {
                return ResourceManager.GetString("TeleportingToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport IPC not found.
        /// </summary>
        internal static string TeleportIPCNotFound {
            get {
                return ResourceManager.GetString("TeleportIPCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Markers.
        /// </summary>
        internal static string TemporaryMarkers {
            get {
                return ResourceManager.GetString("TemporaryMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Map Window.
        /// </summary>
        internal static string ToggleMapWindow {
            get {
                return ResourceManager.GetString("ToggleMapWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the module.
        /// </summary>
        internal static string ToggleModuleHelp {
            get {
                return ResourceManager.GetString("ToggleModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Options.
        /// </summary>
        internal static string ToolbarOptions {
            get {
                return ResourceManager.GetString("ToolbarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Color.
        /// </summary>
        internal static string TooltipColor {
            get {
                return ResourceManager.GetString("TooltipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Config.
        /// </summary>
        internal static string TooltipConfig {
            get {
                return ResourceManager.GetString("TooltipConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Chests.
        /// </summary>
        internal static string TreasureMarkers {
            get {
                return ResourceManager.GetString("TreasureMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unaccepted Quest Color.
        /// </summary>
        internal static string UnacceptedQuestColor {
            get {
                return ResourceManager.GetString("UnacceptedQuestColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Collapse Window on Command.
        /// </summary>
        internal static string UnCollapseWindow {
            get {
                return ResourceManager.GetString("UnCollapseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Region Search.
        /// </summary>
        internal static string UseRegionSearch {
            get {
                return ResourceManager.GetString("UseRegionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use alternative search ui for finding maps.
        /// </summary>
        internal static string UseRegionSearchHelp {
            get {
                return ResourceManager.GetString("UseRegionSearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waymarks.
        /// </summary>
        internal static string Waymarks {
            get {
                return ResourceManager.GetString("Waymarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Focused.
        /// </summary>
        internal static string WhenFocused {
            get {
                return ResourceManager.GetString("WhenFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Moving.
        /// </summary>
        internal static string WhenMoving {
            get {
                return ResourceManager.GetString("WhenMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Unfocused.
        /// </summary>
        internal static string WhenUnFocused {
            get {
                return ResourceManager.GetString("WhenUnFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Window Options.
        /// </summary>
        internal static string WindowOptions {
            get {
                return ResourceManager.GetString("WindowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        internal static string WindowPosition {
            get {
                return ResourceManager.GetString("WindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        internal static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in on Flag.
        /// </summary>
        internal static string ZoomOnFlag {
            get {
                return ResourceManager.GetString("ZoomOnFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zooms on flags when clicking on map location links.
        /// </summary>
        internal static string ZoomOnFlagHelp {
            get {
                return ResourceManager.GetString("ZoomOnFlagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Options.
        /// </summary>
        internal static string ZoomOptions {
            get {
                return ResourceManager.GetString("ZoomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Speed.
        /// </summary>
        internal static string ZoomSpeed {
            get {
                return ResourceManager.GetString("ZoomSpeed", resourceCulture);
            }
        }
    }
}
