//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mappy.System.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mappy.System.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Flag.
        /// </summary>
        internal static string AddFlag {
            get {
                return ResourceManager.GetString("AddFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aethernet Color.
        /// </summary>
        internal static string AethernetColor {
            get {
                return ResourceManager.GetString("AethernetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetheryte Color.
        /// </summary>
        internal static string AetheryteColor {
            get {
                return ResourceManager.GetString("AetheryteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Aetherytes on Top.
        /// </summary>
        internal static string AetherytesOnTop {
            get {
                return ResourceManager.GetString("AetherytesOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Members.
        /// </summary>
        internal static string AllianceMembers {
            get {
                return ResourceManager.GetString("AllianceMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Show Toolbar.
        /// </summary>
        internal static string AlwaysShowToolbar {
            get {
                return ResourceManager.GetString("AlwaysShowToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot teleport in this situation..
        /// </summary>
        internal static string CannotTeleport {
            get {
                return ResourceManager.GetString("CannotTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center on Player.
        /// </summary>
        internal static string CenterOnPlayer {
            get {
                return ResourceManager.GetString("CenterOnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Color.
        /// </summary>
        internal static string CircleColor {
            get {
                return ResourceManager.GetString("CircleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone Angle.
        /// </summary>
        internal static string ConeAngle {
            get {
                return ResourceManager.GetString("ConeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone Radius.
        /// </summary>
        internal static string ConeRadius {
            get {
                return ResourceManager.GetString("ConeRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed Markers.
        /// </summary>
        internal static string DisplayedMarkers {
            get {
                return ResourceManager.GetString("DisplayedMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayOptions.
        /// </summary>
        internal static string DisplayOptions {
            get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Warning Time.
        /// </summary>
        internal static string EarlyWarningTime {
            get {
                return ResourceManager.GetString("EarlyWarningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Integrations.
        /// </summary>
        internal static string EnableIntegrations {
            get {
                return ResourceManager.GetString("EnableIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiringColor.
        /// </summary>
        internal static string ExpiringColor {
            get {
                return ResourceManager.GetString("ExpiringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Warning.
        /// </summary>
        internal static string ExpiringWarning {
            get {
                return ResourceManager.GetString("ExpiringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Mode.
        /// </summary>
        internal static string FadeMode {
            get {
                return ResourceManager.GetString("FadeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Opacity.
        /// </summary>
        internal static string FadePercent {
            get {
                return ResourceManager.GetString("FadePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade When Moving.
        /// </summary>
        internal static string FadeWhenMoving {
            get {
                return ResourceManager.GetString("FadeWhenMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade When Unfocused.
        /// </summary>
        internal static string FadeWhenUnfocused {
            get {
                return ResourceManager.GetString("FadeWhenUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATEs.
        /// </summary>
        internal static string FATEs {
            get {
                return ResourceManager.GetString("FATEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Color.
        /// </summary>
        internal static string FillColor {
            get {
                return ResourceManager.GetString("FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Marker.
        /// </summary>
        internal static string FlagMarker {
            get {
                return ResourceManager.GetString("FlagMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Player.
        /// </summary>
        internal static string FollowPlayer {
            get {
                return ResourceManager.GetString("FollowPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Integrations.
        /// </summary>
        internal static string GameIntegrations {
            get {
                return ResourceManager.GetString("GameIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Area.
        /// </summary>
        internal static string GatheringArea {
            get {
                return ResourceManager.GetString("GatheringArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Points.
        /// </summary>
        internal static string GatheringPoints {
            get {
                return ResourceManager.GetString("GatheringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help message.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Accepted Quests.
        /// </summary>
        internal static string HideAcceptedQuests {
            get {
                return ResourceManager.GetString("HideAcceptedQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide and Unlock.
        /// </summary>
        internal static string HideAndLock {
            get {
                return ResourceManager.GetString("HideAndLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Between Areas.
        /// </summary>
        internal static string HideBetweenAreas {
            get {
                return ResourceManager.GetString("HideBetweenAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Combat.
        /// </summary>
        internal static string HideInCombat {
            get {
                return ResourceManager.GetString("HideInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Duties.
        /// </summary>
        internal static string HideInDuties {
            get {
                return ResourceManager.GetString("HideInDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Levequests.
        /// </summary>
        internal static string HideLeveQuests {
            get {
                return ResourceManager.GetString("HideLeveQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Unaccepted Quests.
        /// </summary>
        internal static string HideUnacceptedQuests {
            get {
                return ResourceManager.GetString("HideUnacceptedQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window Frame.
        /// </summary>
        internal static string HideWindowFrame {
            get {
                return ResourceManager.GetString("HideWindowFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide With Game GUI.
        /// </summary>
        internal static string HideWithGameGui {
            get {
                return ResourceManager.GetString("HideWithGameGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses.
        /// </summary>
        internal static string HousingMarkers {
            get {
                return ResourceManager.GetString("HousingMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Configuration.
        /// </summary>
        internal static string IconConfig {
            get {
                return ResourceManager.GetString("IconConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string IconScale {
            get {
                return ResourceManager.GetString("IconScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Selection.
        /// </summary>
        internal static string IconSelection {
            get {
                return ResourceManager.GetString("IconSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Quest Color.
        /// </summary>
        internal static string InProgressColor {
            get {
                return ResourceManager.GetString("InProgressColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When placing a flag on the map, insert &lt;flag&gt; into chat
        ///Recommended to disable if using Chat2.
        /// </summary>
        internal static string InsertFlagHelp {
            get {
                return ResourceManager.GetString("InsertFlagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert &lt;flag&gt; in chat.
        /// </summary>
        internal static string InsertFlagInChat {
            get {
                return ResourceManager.GetString("InsertFlagInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Link Color.
        /// </summary>
        internal static string InstanceLinkColor {
            get {
                return ResourceManager.GetString("InstanceLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces all of the games normal map functions with Mappy functions instead.
        /// </summary>
        internal static string IntegrationsDescription {
            get {
                return ResourceManager.GetString("IntegrationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Open.
        /// </summary>
        internal static string KeepOpen {
            get {
                return ResourceManager.GetString("KeepOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the order that markers are drawn, higher values will be shown on top of lower values..
        /// </summary>
        internal static string LayerHelp {
            get {
                return ResourceManager.GetString("LayerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levequest Color.
        /// </summary>
        internal static string LeveQuestColor {
            get {
                return ResourceManager.GetString("LeveQuestColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Window Position.
        /// </summary>
        internal static string LockWindow {
            get {
                return ResourceManager.GetString("LockWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Link Color.
        /// </summary>
        internal static string MapLinkColor {
            get {
                return ResourceManager.GetString("MapLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Markers.
        /// </summary>
        internal static string MapMarkers {
            get {
                return ResourceManager.GetString("MapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Markers.
        /// </summary>
        internal static string MiscMarkers {
            get {
                return ResourceManager.GetString("MiscMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Colors.
        /// </summary>
        internal static string ModuleColors {
            get {
                return ResourceManager.GetString("ModuleColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Config.
        /// </summary>
        internal static string ModuleConfig {
            get {
                return ResourceManager.GetString("ModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Options.
        /// </summary>
        internal static string ModuleOptions {
            get {
                return ResourceManager.GetString("ModuleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Flag Here.
        /// </summary>
        internal static string MoveFlag {
            get {
                return ResourceManager.GetString("MoveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration Window.
        /// </summary>
        internal static string OpenConfigWindow {
            get {
                return ResourceManager.GetString("OpenConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Color.
        /// </summary>
        internal static string OutlineColor {
            get {
                return ResourceManager.GetString("OutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Thickness.
        /// </summary>
        internal static string OutlineThickness {
            get {
                return ResourceManager.GetString("OutlineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Members.
        /// </summary>
        internal static string PartyMembers {
            get {
                return ResourceManager.GetString("PartyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string QuestMarkers {
            get {
                return ResourceManager.GetString("QuestMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Flag.
        /// </summary>
        internal static string RemoveFlag {
            get {
                return ResourceManager.GetString("RemoveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Gathering Area.
        /// </summary>
        internal static string RemoveGatheringArea {
            get {
                return ResourceManager.GetString("RemoveGatheringArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for map.
        /// </summary>
        internal static string SearchForMap {
            get {
                return ResourceManager.GetString("SearchForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show and Unlock.
        /// </summary>
        internal static string ShowAndUnlock {
            get {
                return ResourceManager.GetString("ShowAndUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cone.
        /// </summary>
        internal static string ShowCone {
            get {
                return ResourceManager.GetString("ShowCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon.
        /// </summary>
        internal static string ShowIcon {
            get {
                return ResourceManager.GetString("ShowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Misc Tooltips.
        /// </summary>
        internal static string ShowMiscTooltips {
            get {
                return ResourceManager.GetString("ShowMiscTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows tooltips for map icons such as &quot;Repair&quot;, &quot;Shop&quot;, &quot;Trader.
        /// </summary>
        internal static string ShowMiscTooltipsHelp {
            get {
                return ResourceManager.GetString("ShowMiscTooltipsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Circle.
        /// </summary>
        internal static string ShowRing {
            get {
                return ResourceManager.GetString("ShowRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toolbar on Hover.
        /// </summary>
        internal static string ShowToolbarOnHover {
            get {
                return ResourceManager.GetString("ShowToolbarOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltip.
        /// </summary>
        internal static string ShowTooltip {
            get {
                return ResourceManager.GetString("ShowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Marker Color.
        /// </summary>
        internal static string StandardColor {
            get {
                return ResourceManager.GetString("StandardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the teleport function, you must install the &apos;Teleporter&apos; plugin.
        /// </summary>
        internal static string TeleporterMissingError {
            get {
                return ResourceManager.GetString("TeleporterMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting to {0}..
        /// </summary>
        internal static string TeleportingToLocation {
            get {
                return ResourceManager.GetString("TeleportingToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport IPC not found.
        /// </summary>
        internal static string TeleportIPCNotFound {
            get {
                return ResourceManager.GetString("TeleportIPCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Color.
        /// </summary>
        internal static string TooltipColor {
            get {
                return ResourceManager.GetString("TooltipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Config.
        /// </summary>
        internal static string TooltipConfig {
            get {
                return ResourceManager.GetString("TooltipConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Chests.
        /// </summary>
        internal static string TreasureMarkers {
            get {
                return ResourceManager.GetString("TreasureMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waymarks.
        /// </summary>
        internal static string Waymarks {
            get {
                return ResourceManager.GetString("Waymarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Focused.
        /// </summary>
        internal static string WhenFocused {
            get {
                return ResourceManager.GetString("WhenFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Moving.
        /// </summary>
        internal static string WhenMoving {
            get {
                return ResourceManager.GetString("WhenMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Unfocused.
        /// </summary>
        internal static string WhenUnFocused {
            get {
                return ResourceManager.GetString("WhenUnFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Window Options.
        /// </summary>
        internal static string WindowOptions {
            get {
                return ResourceManager.GetString("WindowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Speed.
        /// </summary>
        internal static string ZoomSpeed {
            get {
                return ResourceManager.GetString("ZoomSpeed", resourceCulture);
            }
        }
    }
}
