//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mappy.System.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mappy.System.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Members.
        /// </summary>
        internal static string AllianceMembers {
            get {
                return ResourceManager.GetString("AllianceMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATEs.
        /// </summary>
        internal static string FATEs {
            get {
                return ResourceManager.GetString("FATEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Marker.
        /// </summary>
        internal static string FlagMarker {
            get {
                return ResourceManager.GetString("FlagMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Area.
        /// </summary>
        internal static string GatheringArea {
            get {
                return ResourceManager.GetString("GatheringArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Points.
        /// </summary>
        internal static string GatheringPoints {
            get {
                return ResourceManager.GetString("GatheringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses.
        /// </summary>
        internal static string HousingMarkers {
            get {
                return ResourceManager.GetString("HousingMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Configuration.
        /// </summary>
        internal static string IconConfig {
            get {
                return ResourceManager.GetString("IconConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string IconScale {
            get {
                return ResourceManager.GetString("IconScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Markers.
        /// </summary>
        internal static string MapMarkers {
            get {
                return ResourceManager.GetString("MapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string QuestMarkers {
            get {
                return ResourceManager.GetString("QuestMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon.
        /// </summary>
        internal static string ShowIcon {
            get {
                return ResourceManager.GetString("ShowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltip.
        /// </summary>
        internal static string ShowTooltip {
            get {
                return ResourceManager.GetString("ShowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Chests.
        /// </summary>
        internal static string TreasureMarkers {
            get {
                return ResourceManager.GetString("TreasureMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waymarks.
        /// </summary>
        internal static string Waymarks {
            get {
                return ResourceManager.GetString("Waymarks", resourceCulture);
            }
        }
    }
}
